### ISSUE TITLE
Investigate ECONNRESET issue during "zipdeploy" call

### ISSUE THREAD

**Issue by ejizba** [microsoft/vscode-azurefunctions#2844]
Creating this issue as a catch-all for the "ECONNRESET" errors being reported specifically for the "zipdeloy" call. Usually a retry helps fix these errors, but it's possible our retry logic isn't working in this case because it's using a stream to send the zip file and I don't know if we handle restarting the stream on a retry.

It's also possible this could be caused by especially large zip files or especially slow internet.

### Update April 13, 2022

The 1.66.0 VS Code update resulted in many users encountering ECONNRESET and 400 Bad Request errors when attempting to deploy their app. A fix has been released in version [v1.6.2](https://github.com/microsoft/vscode-azurefunctions/releases/tag/v1.6.2) of the extension. [(comment)](https://github.com/microsoft/vscode-azurefunctions/issues/2844#issuecomment-1098393527)

**Comment by blomm** [comment]
just tried 1.6, and it's [still the case for me](https://github.com/microsoft/vscode-azurefunctions/issues/2795) that any version 1.3.0 or greater fails with this error, so I'll stick to the version just before 1.3.0, 1.2.1 where it works just fine.

**Comment by miszu** [comment]
I'm experiencing the same (I think) issues as @blomm - deploy of TypeScript Azure Functions project does not work from VS Code with v1.6 (ECONNRESET), works fine after downgrading to 1.2.1. Let me know if I could provide more info for the investigation

**Comment by transcendent** [comment]
Had the exact same issue and downgrading the Azure functions extension resolved it. Note that I had a whole bunch of issues deploying via Github actions which is why I moved to doing the deployment through the extension instead. My function app is quite large (~10 individual functions).

**Comment by nturinski** [comment]
The only change between v1.3.0 and v1.2.1 that I can see that would impact the ECONNRESET error is right here: https://github.com/microsoft/vscode-azuretools/commit/c6d587c7dbef79f3e00bafcf0e9a096d4d1d97eb#diff-193b27d62e4fbda3d563009fed5ec6761a05f73558d94b39fab63ae948c679eaR38

Between versions, we updated the `vscode-azureappservice` package from 0.72.1 to 0.73.0:
https://github.com/microsoft/vscode-azurefunctions/commit/5de6996b6917f6a456b06f922a63e2f6611af43c#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R1130

The only change between those versions is updating the ui package:
https://github.com/microsoft/vscode-azuretools/commit/9c15e6fc45179181b2b46901b2eb0b42e09f8e1a

Where we updated `ms-rest-js`
https://github.com/microsoft/vscode-azuretools/commit/c6d587c7dbef79f3e00bafcf0e9a096d4d1d97eb

So seems like we should start our investigation from there. 🔍

**Comment by cek-cek** [comment]
Ran into the issue yesterday after updating VS Code (I update frequently, so that it worked before should not have been caused by using some outdated version). Suddenly all TypeScript deployments got stuck just after the zip is created (`Zip package size: X MB` in the output) and eventually time out with ECONNRESET error for url `https://xxx.scm.azurewebsites.net/api/zipdeploy?isAsync=true&author=VS Code`.

I've tried everything from reinstalling Core Tools, rebooting, using different app service plan and waiting several hours (as I've read ECONNRESET in Azure is usually only transient issue), but only thing that makes this work again is downgrading to the previously mentioned year old release 1.2.1, where the zip creation is immediately followed by output `Fetching changes.` and eventually successfully completes.

**Comment by sven5** [comment]
Same issue here. After today's update of VSCode the Logic Apps deployment doesn't work anymore.

**Comment by blomm** [comment]
can we treat this issue seriously yet @ejizba?
I'm still scared to perform any upgrades around the Azure Functions extension, sticking to 1.2.1

**Comment by cek-cek** [comment]
One more problem with the v1.2.1 workaround - turns out this does not accept ~4 as a functions target version, only ~1 - ~3, which effectively constraints to use manual CLI publish if you need to target ~4.

**Comment by aLucaz** [comment]
Same error using VSCode 1.66.0

**Comment by ejizba** [comment]
Based on the number of comments within several hours, I'm guessing this is a new issue related to the release of VS Code 1.66. Does it reproduce if you use the previous version of VS Code? I checked the release notes and the only thing I saw that could be related is they bumped from Node.js v14 to v16.

I'm not on this particular team anymore, but hopefully @nturinski @alexweininger or @bwateratmsft could take a look relatively soon.

@sven5 the logic apps extension is a different extension/team - you'll have to follow up with them separately.

**Comment by alexweininger** [comment]
Users created an issue on VS Code: https://github.com/microsoft/vscode/issues/146470

I'm able to reproduce the issue on `1.67.0-insider`.
<details>
<summary>VS Code version details</summary>

```
Version: 1.67.0-insider (Universal)
Commit: 909602cf04e0fa42528d692676d0d4e15e67bba2
Date: 2022-03-31T11:04:00.413Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Darwin x64 21.4.0
```

</details>

I agree that this seems to be related to the `1.66.0` VS Code release due to the timing of the issue reports. Further backed up by [comments saying zip deploy worked again after reverting to `1.65.2`](https://github.com/microsoft/vscode/issues/146470#issuecomment-1085077508).

As for the issue itself, I'm not immediately sure how upgrading from Node.JS v14 to v16 could break zip deploy, but we'll investigate. 🕵️

**Comment by ShawnMcGough** [comment]
Also having this issue. 

Could be from [VSCode Azure SDK for Node.js - App Service Tools](https://github.com/microsoft/vscode-azuretools/tree/main/appservice).

Which appears to [silently failing unit tests](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=44725&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=af8077e2-e4a3-553c-8cd9-22d819351f40)? I'm not sure, but those look like errors from the log, yet reporting successful test cases. Which maybe why it wasn't caught pre-release.

Should an issue be opened on the Azure SDK for Node.js repo?

**Comment by aLucaz** [comment]
An alternative if someone is looking for another option (this is using Azure Functions Core Tools (4.x or later) and Azure CLI (2.4 or later)): 

```
#!/bin/bash
# $1 => folder or file name to be zipped
# $2 => function app name
# $3 => resource group name

ZIP_NAME=`date "+%Y%m%d%H%M%S.zip"`
cd $1
zip -r ${ZIP_NAME} . > /dev/null 2>&1
echo "File zipped"
az functionapp deployment source config-zip -n $2 -g $3 --src ${ZIP_NAME}
rm ${ZIP_NAME}
```

open to suggestions

**Comment by eshy** [comment]
Was having the same issue. Reverting to 16.5.2 did solve it

**Comment by klodha** [comment]
Same issue, VS Code updated to March 2022 release and suddenly deployments stopped. All I see in logs was creating a zip file and then after long wait an error to call zipdeploy API. Tried all options but eventually downgrading to 1.65 helped. 

Not sure what is the root issue, but there is something breaking between the two releases when it comes to Azure functions.

**Comment by dangater** [comment]
This issue has been plaguing me for days but downgrading VS Code to 1.65.2 solved it instantly.

**Comment by cutty201** [comment]
I can't believe it -- I search internet -- and you kind people are right -- the new update broke all this -- I couldnt even get LocalGit to work right . Thanks for the downgrade suggestion - its working again for me

**Comment by sven5** [comment]
The only way seems to be a downgrade.

**Comment by Deico-Karel** [comment]
I downgrade to https://code.visualstudio.com/updates/v1_65 works fine

**Comment by alexweininger** [comment]
Until a fix is released in VS Code stable (hopefully the next major release), here are some options:
1. Wait for the fix to come in [VS Code Insiders](https://code.visualstudio.com/insiders/)
2. [Deploy via Azure CLI](https://github.com/microsoft/vscode-azurefunctions/issues/2844#issuecomment-1086259916)
3. Downgrade your Azure Functions extension version to `1.2.1` (Feb 08, 2021), we used a different zip deploy method which seems to be working still. Note: it might not work in environments like WSL or Codespaces, which is why we changed our deploy in `1.3.0` (Mar 15, 2021).
4. Downgrade to the [VS Code February 2022 release](https://code.visualstudio.com/updates/v1_65), where zip deploy is working as discussed and confirmed above.
---

Here's some information on the bug we suspect is causing the issue with zip deploy.

We suspect that it was a regression in the [libuv library](https://github.com/libuv/libuv) caused by [libuv/libuv@ce15b84](https://github.com/libuv/libuv/commit/ce15b8405e9d01e221f8390475deab4a40d26e38), which was included in Node.JS `16.13.0`.

See [this issue](https://github.com/microsoft/vscode/issues/146470), and specifically [this comment](https://github.com/microsoft/vscode/issues/146470#issuecomment-1087175293) for more information.

**Comment by ChristSent** [comment]
Downgraded vs code, by simply running the installer from here: https://code.visualstudio.com/updates/v1_65

**Comment by carantygit** [comment]
> Downgraded vs code, by simply running the installer from here: https://code.visualstudio.com/updates/v1_65

A fix of the extensión or VS Code version will be a better solution :). But for now, any of this options works. Thanks

**Comment by paladin2005** [comment]
They updated vscode and it is fixed for me now

**Comment by boehlerlukas** [comment]
@paladin2005 too bad, I just downgraded, and it fixed it for me as well. Will try upgrading now :)

**Comment by klodha** [comment]
> They updated vscode and it is fixed for me now
Not sure, as current version (including the latest Insider build) of VS code doesn't work. Only option for now is to downgrade VS Code to 1.65.x.

**Comment by paladin2005** [comment]
> > They updated vscode and it is fixed for me now
> > Not sure, as current version (including the latest Insider build) of VS code doesn't work. Only option for now is to downgrade VS Code to 1.65.x.

I don't know why to downvote me, I am telling you I had that problem too, VScode updated and start working, and my client was waiting for some changes. 
in my case, I couldn't deploy the "publish" folder in my backend and the "dist" folder on my frontend, it was getting stuck when creating the zip file to publish. I saw an update and tried again and it worked again.
Was this update: [Vscode 1.66.1](https://github.com/microsoft/vscode/releases/tag/1.66.1)

**Comment by gleysonlf** [comment]
> > > They updated vscode and it is fixed for me now
> > > Not sure, as current version (including the latest Insider build) of VS code doesn't work. Only option for now is to downgrade VS Code to 1.65.x.
> 
> I don't know why to downvote me, I am telling you I had that problem too, VScode updated and start working, and my client was waiting for some changes. in my case, I couldn't deploy the "publish" folder in my backend and the "dist" folder on my frontend, it was getting stuck when creating the zip file to publish. I saw an update and tried again and it worked again. Was this update: [Vscode 1.66.1](https://github.com/microsoft/vscode/releases/tag/1.66.1)

It didn't work for me:

VS Code: 1.66.1
Azure App Service: 0.23.1
Azure Functions: 1.6.1


**It worked was to downgrade to VS Code 1.65.2**

**Comment by klodha** [comment]
@paladin2005 Understood. There seems to be some misunderstanding due to language gaps perhaps. 

Do you want to say that: your VSCode also got updated to 1.66 and you started working on some changes which client asked. But when you tried to upload, it failed. 

If that is the part with "update", you are absolutely correct. Everyone started facing the problem with this update to version 1.66.

Only solution which worked for others (and most likely for you also) is to downgrade to 1.65 release of VSCode.

**Comment by rdeveen** [comment]
Alternative one-line deployment use `func azure functionapp publish <FunctionAppName>`

See: https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local?tabs=v4%2Cwindows%2Ccsharp%2Cportal%2Cbash#project-file-deployment

**Comment by alexweininger** [comment]
Hey everyone,

I believe to have found a fix. If anyone can help verify the fix for me that would be a big help!

Steps to install extension development build:
1. If needed, update VS Code to `1.66.0` or greater.
1. Download the extension .VSIX from our Azure DevOps Pipeline [View artifacts artifacts](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=45131&view=artifacts&pathAsName=false&type=publishedArtifacts) | [Direct download link](https://dev.azure.com/ms-azuretools/_apis/resources/Containers/5753365/vsix?itemPath=vsix%2Fvscode-azurefunctions-1.6.2-alpha.vsix)
1. From the command palette (`F1` or `Command/Ctrl + Shift + P`), run the "Extensions: Install from VSIX..." command.
1. Select the downloaded .VSIX file, then reload VS Code as prompted.

Once installed, attempt to deploy your app as normal. Report back and let us know if deployment succeeded/failed. 

Thanks!

**Comment by klodha** [comment]
Thanks @alexweininger, I will give it a try in few minutes.

**Comment by chazix** [comment]
@alexweininger - I just tried here, installed v1.6.2-alpha from the vsix on v1.66.0 vscode. I received the same error unfortunately: `1:55:34 AM: Error: request to https://rawmengame-tournament.scm.azurewebsites.net/api/zipdeploy?isAsync=true&author=VS%20Code failed, reason: read ECONNRESET`

**Comment by alexweininger** [comment]
@chazix thanks for taking the time to verify. Could you try again with the [updated steps](https://github.com/microsoft/vscode-azurefunctions/issues/2844#issuecomment-1095673285)? Thanks!

**Comment by klodha** [comment]
> Thanks @alexweininger, I will give it a try in few minutes.

@alexweininger, I tried using updated plugin (Zip package size: 4.96 MB) and it seems to be working 🎉 I would say a bit slower though (but that could be some network glitch or due to plugin being alpha). 

I have included my plugin configuration and VS Code version details here. 

<img width="859" alt="image" src="https://user-images.githubusercontent.com/1103986/163106916-3a8f8bf5-4396-46fb-b734-4736c3629d79.png">

<img width="250" alt="image" src="https://user-images.githubusercontent.com/1103986/163106936-fcae8a12-6d86-4f05-91b1-34510cec3d33.png">

I am happy that you finally found the fix 👍🏻. Looking forward for some technical details about the same (for learning) as well general release of this update for the plugin.

**Comment by tommyhtran** [comment]
@alexweininger
I can confirm v1.6.2-alpha works.
![image](https://user-images.githubusercontent.com/43150734/163183627-f79097de-0606-41aa-accc-2dcbaa230780.png)

**Comment by stefano24** [comment]
> Hi everyone,
> 
> I believe to have found a fix. If anyone can help verify the fix for me that would be a big help!
> 
> Steps to install extension development build:
> 
> 1. If needed, update VS Code to `1.66.0` or greater.
> 2. Download the extension .VSIX from our Azure DevOps Pipeline - [Direct download link](https://dev.azure.com/ms-azuretools/534e1e1c-b364-44d0-b5ee-dce879a5106e/_apis/build/builds/45131/artifacts?artifactName=vsix&api-version=7.0&%24format=zip) | [View artifacts](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=45131&view=artifacts&pathAsName=false&type=publishedArtifacts)
> 3. Extract the .vsix file from the .zip folder
> 4. From the command palette (`F1` or `Command/Ctrl + Shift + P`), run the "Extensions: Install from VSIX..." command.
> 5. Select the downloaded .vsix file, then reload VS Code as prompted.
> 6. Navigate to the extensions view and verify the version is `1.6.2-alpha`
>    ![Screen Shot 2022-04-12 at 12 19 33 PM](https://user-images.githubusercontent.com/12476526/163037446-e8232513-1fe6-4d50-83dd-ef155063ab4b.png)
> 
> Once installed, attempt to deploy your app as normal. Report back and let us know if deployment succeeded/failed.
> 
> Thanks!

I can confirm, with version 1.6.2-alpha works!

**Comment by alexweininger** [comment]
Fix has been released in version [v1.6.2](https://github.com/microsoft/vscode-azurefunctions/releases/tag/v1.6.2) of the extension. 

Huge thank you to everyone who helped verify the fix! ❤️

**Comment by klawrawkz** [comment]
Hi, my name is klawrawkz. I am fine. How are you?

It's not fixed for me. Nope. Not at all.

**Hi ho, hi ho, it's off to work I go...**

_Tryin to get some work done..._
<img width="655" alt="image" src="https://user-images.githubusercontent.com/48074223/164538626-9a2c33f7-23c8-4e74-9384-5d689fe8f025.png">

_La, la, la, ... tryin to get some work done..._
<img width="342" alt="image" src="https://user-images.githubusercontent.com/48074223/164537850-c7e837c9-4477-49f1-8fba-de305459b9fa.png">

_Hmm, mmm, mmm, ...tryin to get some work done..._
<img width="485" alt="image" src="https://user-images.githubusercontent.com/48074223/164539340-d7e5cc44-412b-4c4b-bb37-886e7146a980.png">

I'm not in the error biznizz, so this is no fun, my babe, no fun....

@alexweininger, what am I missing here?

Hope you are well.

klaw

**Comment by masakawa527** [comment]
I get the same error when deploying Logic Apps Standard.
This does not appear to have been resolved.
![image](https://user-images.githubusercontent.com/101319740/165528335-bd0083ff-cdb8-439c-87c8-30b5fd014871.png)

How can I get the same error when deploying from VSCode and using

**Comment by tommyhtran** [comment]
@alexweininger,
klawrawkz and masakawa527 seem to be having a problem with the Azure Logic Apps (Standard) extension. I recommend closing this issue as it's resolved for the Azure Functions extension.

**Comment by klawrawkz** [comment]
All,

Regarding @masakawa527's suggestion, I think it would be premature to close this issue without or before it is demonstrated and proven that this "logic" issue is not related to the original "function extension" bug.   It is my understanding that "logic apps" depend on the "function app" extension. It seems reasonable to suggest that this error is not isolated in the "logic" extension, but perhaps originates from the function portion of the two codependent extensions. What say you? 

It is also important to preserve this thread because of the relationship between logic and function extensions. If this issue is closed, is there an open issue specific to "logic apps" related to this?

**Comment by blomm** [comment]
1.7.3 just released, somehow my VS code extension automatically upgraded me to this.
Still doesn't deploy, "socket hang up" this time, I've reinstalled old trusty version 1.2.1

**Comment by esdccs1** [comment]
I had this issue while trying to publish a logic app...
```
vscode 1.68
vscode-azurefunction version 1.7.3
```

I ended up targeting my log app via the command line instead (Since I figure this is what the vscode extension is doing behind the scenes)
```
cd root_logic_app_folder      #holding host.json, connections.json and all the workflow.json folders 
func azure functionapp publish my-logic-app-name-resource           #where this name is the logic app in your resource group
```

**Comment by nturinski** [comment]
Hi @klawrawkz. Regarding this statement:
>  It is my understanding that "logic apps" depend on the "function app" extension.

This is actually not correct. A long time ago, the Logic Apps extension cloned the Functions Apps extension and then continued to build their extension from there. That means any fixes in Functions does not automatically get picked up by Logic Apps.

This was fixed in the package `@microsoft/vscode-azext-azureappservice` in v0.6.2. The Logics Apps extension didn't update that package until June. But now that it is updated, this issue hasn't been reported so I will close this as fixed.
