### ISSUE TITLE
400 BadRequest when Publishing Azure App

### ISSUE THREAD

**Issue by mdixon-equinix** [microsoft/vscode-azurefunctions#3105]
We have written th
Issue Type: <b>Bug</b>

I haven't opened VS Code in about a week. Previously I was able to easily publish to my Azure Function app. Now after the latest VS Code update, I am unable to publish my functions.  I receive the following error each time I attempt it:

11:03:57 AM eqix-automation-dev: Starting deployment...
11:03:58 AM eqix-automation-dev: Creating zip package...
11:03:58 AM eqix-automation-dev: Zip package size: 48.6 kB
11:07:58 AM: Error: 400.0 BadRequest

Extension version: 1.6.1
VS Code version: Code 1.66.1 (8dfae7a5cd50421d10cd99cb873990460525a898, 2022-04-06T14:50:12.141Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) E-2276M  CPU @ 2.80GHz (12 x 2808)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.76GB (19.19GB free)|
|Process Argv|--crash-reporter-id f981abc5-56ff-448f-922b-3c168723e687|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
pynewfile477:30463512

```

</details>

e needed data into your clipboard because it was too large to send. Please paste.

**Comment by alexweininger** [comment]
Sorry you ran into this bug, the good news is we are working on a fix for this right now, and we have a development build available if you'd like to try and verify the fix works for us.

---

Steps to install extension development build:
1. If needed, update VS Code to `1.66.0` or greater.
1. Download the extension .VSIX from our Azure DevOps Pipeline - [Direct download link](https://dev.azure.com/ms-azuretools/_apis/resources/Containers/5753365/vsix?itemPath=vsix%2Fvscode-azurefunctions-1.6.2-alpha.vsix) | [View artifacts](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=45131&view=artifacts&pathAsName=false&type=publishedArtifacts)
1. From the command palette (`F1` or `Command/Ctrl + Shift + P`), run the "Extensions: Install from VSIX..." command.
1. Select the downloaded .VSIX file, then reload VS Code as prompted.
1. Navigate to the extensions view and verify the version is `1.6.2-alpha`
![Screen Shot 2022-04-12 at 12 19 33 PM](https://user-images.githubusercontent.com/12476526/163037446-e8232513-1fe6-4d50-83dd-ef155063ab4b.png)

Once installed, attempt to deploy your app as normal. Please let us know if deployment succeeded/failed.

---

Follow along with #2844 for more updates and discussion, we're directing all of these zip deploy issues over there.

**Comment by alexweininger** [comment]
Closing as a duplicate of #2844

**Comment by alexweininger** [comment]
Fix has been released in version [v1.6.2](https://github.com/microsoft/vscode-azurefunctions/releases/tag/v1.6.2) of the extension.

**Comment by clohl** [comment]
This issue is not resolved - I'm still having receiving a 400.0 Bad Request upon deployment using v1.6.2 today
3:21:53 PM : Starting deployment...
3:21:54 PM l: Creating zip package...
3:22:34 PM: Error: 400.0 BadRequest

I've tried uninstalling / reinstalling the plugin & doing a system reboot.  Regardless I always receive a 400.0 Bad Request when deploying to an Function App created via VS Code today, and I get a hang on Uploading Zip Package to any Function Apps created via portal, or VS Code (advanced)

VSCode -
Version: 1.66.2 (user setup)
Date: 2022-04-11T07:46:01.075Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
v8: 9.8.177.11-electron.0
OS:Windows_NT x64 10.0.19044

Azure Functions Plugin:
Version: 1.6.2
last updated: 4/13/2022, 12:08:23

**Comment by alexweininger** [comment]
> This issue is not resolved - I'm still having receiving a 400.0 Bad Request upon deployment using v1.6.2 today 3:21:53 PM : Starting deployment... 3:21:54 PM : Creating zip package... 3:22:34 PM: Error: 400.0 BadRequest
> 
> I've tried uninstalling / reinstalling the plugin & doing a system reboot. Regardless I always receive a 400.0 Bad Request when deploying to an Function App created via VS Code today, and I get a hang on Uploading Zip Package to any Function Apps created via portal, or VS Code (advanced)
> 
> VSCode - Version: 1.66.2 (user setup) Date: 2022-04-11T07:46:01.075Z Electron: 17.2.0 Chromium: 98.0.4758.109 Node.js: 16.13.0 v8: 9.8.177.11-electron.0 OS:Windows_NT x64 10.0.19044
> 
> Azure Functions Plugin: Version: 1.6.2 last updated: 4/13/2022, 12:08:23

Can you try using the [February 2022 v1.65.0](https://code.visualstudio.com/updates/v1_65) release of VS Code?

**Comment by clohl** [comment]
> > This issue is not resolved - I'm still having receiving a 400.0 Bad Request upon deployment using v1.6.2 today 3:21:53 PM : Starting deployment... 3:21:54 PM : Creating zip package... 3:22:34 PM: Error: 400.0 BadRequest
> > I've tried uninstalling / reinstalling the plugin & doing a system reboot. Regardless I always receive a 400.0 Bad Request when deploying to an Function App created via VS Code today, and I get a hang on Uploading Zip Package to any Function Apps created via portal, or VS Code (advanced)
> > VSCode - Version: 1.66.2 (user setup) Date: 2022-04-11T07:46:01.075Z Electron: 17.2.0 Chromium: 98.0.4758.109 Node.js: 16.13.0 v8: 9.8.177.11-electron.0 OS:Windows_NT x64 10.0.19044
> > Azure Functions Plugin: Version: 1.6.2 last updated: 4/13/2022, 12:08:23
> 
> Can you try using the [February 2022 v1.65.0](https://code.visualstudio.com/updates/v1_65) release of VS Code?
> 
> Also can you verify that your Azure Functions extension is on the latest version, 1.6.2? ![image](https://user-images.githubusercontent.com/12476526/163281717-f1e17a3e-bb9b-4fee-8023-f473e1bb1e3d.png)

As my previous message states - I'm using 1.6.2 currently on 1.66.  After reverting to 1.65 and validating that AZ Functions v1.6.2 is installed on 1.65 I attempted to publish again and received the same error:
3:59:57 PM dailyArsEmailer: Starting deployment...
3:59:58 PM dailyArsEmailer: Creating zip package...
4:00:38 PM: Error: 400.0 BadRequest

**Comment by nturinski** [comment]
Could you let us know what type of function app that you are trying to deploy?

Also, sometimes Azure's intermittently services go down, so retrying the deployment can resolve some of these issues.

**Comment by clohl** [comment]
Sure – I’m deploying simple NodeJS 16.0 apps with a timerTrigger.  It’s still not working – I’m able to deploy via command line by creating a manual zip package and pushing with az cli.  I’ve tried sporadically throughout the day but VSCode is still throwing the following errors:

3:04:12 PM dailyAmpUpdate: Starting deployment...
3:04:20 PM dailyAmpUpdate: Creating zip package...
3:20:15 PM: Error: request to https://dailyampupdate.scm.azurewebsites.net/api/zipdeploy?isAsync=true&author=VS%20Code failed, reason: socket hang up

3:41:03 PM dailyARSEmailer: Starting deployment...
3:41:10 PM dailyARSEmailer: Creating zip package...
3:41:49 PM: Error: 400.0 BadRequest

I was just trying to test the app before I integrate into CI/CD in GitHub, and I usually just do a push from VSCode to stub out a new service and make sure things execute as expected in Azure…


Chris Lohl
Senior Vice President, Technology
***@***.******@***.***>
p 480 346 1477<tel:480-346-1477>
c 480 717 0389<tel:480-717-0389>

**Comment by nturinski** [comment]
Sorry for making you jump through all of these hoops, but could you try downgrading the extension to v1.61 and downgrade VS Code to v1.6.5?  From your logs, it seems like the zip file isn't being created anymore which is very unusual behavior. 

You can change the Functions version by going into the "Extensions" view and clicking the gear on the Azure Functions extension.

![image](https://user-images.githubusercontent.com/5290572/163489778-2d550e75-82c0-49d9-94d7-585a5553cfa7.png)

**Comment by clohl** [comment]
No dice:
![image](https://user-images.githubusercontent.com/75269027/163491408-f7086617-ce48-4748-83af-a8a56c31c353.png)
![image](https://user-images.githubusercontent.com/75269027/163491605-d2505820-8de5-4402-ac6e-8a1f4d9a9dd0.png)

**Comment by killinterpol** [comment]
Did a new VS Code install on a freshly imaged OS and was able to pull from GitHub and deploy.  This leads me to believe the update of VS Code is not working on my PC.  Potentially a disk or OS issue.  I think the can be resolved for now.  Could be the updater/installer but too many moving parts to say for sure.

**Comment by nturinski** [comment]
@killinterpol  Thanks so much for following up with a resolution.  Yeah, this is very difficult for us to determine what the root issue is, but definitely something weird going on.  It seemed like the zipping wasn't even working at all anymore.

I'll go ahead and close this issue.  Thanks again for filing, using our extension, and working with us so much to try to figure this out!
