### ISSUE TITLE
There is no Function App in the resource list when executing "Deploy to Function App..." command from command palette

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#3170]
**OS:** All
**Azure Resource Extension Build Version:** 20220515.1
**Azure Function Extension build Version:** 20220513.15

**Repro Steps:**
1. Create and open a project in VS Code.
2. Create a Function App.
3. F1 -> Select "Azure Functions: Deploy to Function App...".
4. Check whether the Function App shows in the resource list or not.

**Expect:**
The Function App shows in the resource list.

**Actual:**
There is no Function App in the resource list.
![image](https://user-images.githubusercontent.com/45614674/168562107-1f9d2dfe-5220-4a5a-99cc-7540321ceb96.png)

**More Info:**
This issue also reproduces for other commands, such as "Create Slot.../Add New Setting.../Browse website" and so on.

**Comment by fiveisprime** [comment]
Ran into this one myself while testing the student account 😅

**Comment by alexweininger** [comment]
@fiveisprime it should be fixed now. If you're on the latest versions of RGs and Functions and it still repros let me know.

**Comment by joshtransient** [comment]
This issue still occurs for me, on a fresh install of VSCode (v1.67.2), with fresh installs of extensions on latest versions.
