### ISSUE TITLE
Fail to debug a C# project created with Azure Blob Storage trigger template function

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-azurefunctions#3710]
**OS:** All
**Azure Function Extension Version:** v1.11.0

**Repro Steps:**

1. Create a C# project with "Azure Blob Storage trigger" template.
2. F5.
3. Check whether succeeds to debug the project.

**Expect:**
Succeed to debug the project.

**Actual:**
Fail to debug the project.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/107091828/c66076a2-0629-4a99-aaf0-e17c864f352e)
![image](https://github.com/microsoft/vscode-azurefunctions/assets/107091828/dd9989ae-490d-4b71-98a7-272da67b63bd)

**Comment by nturinski** [comment]
Could you verify this bug again with the build on main? We believe this was fixed by #3756

**Comment by v-chenzha** [comment]
@nturinski  Verified this issue on the latest build 20230716.1, it still reproduces for now.
