### ISSUE TITLE
Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:5858)

### ISSUE THREAD

**Issue by ahmadawais** [Microsoft/vscode-azurefunctions#387]
I'm facing a weird issue.

Error:

```
Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:5858).
```

```
VSCode 1.23.1
MacOS 
Node: 10.1.0
OS: macOS Sierra
npm: 6.0.1
Chrome: 66.0.3359.181
```

Launch.json

```json
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Attach to JavaScript Functions",
			"type": "node",
			"request": "attach",
			"port": 5858,
			"protocol": "inspector",
			"preLaunchTask": "runFunctionsHost"
		}
	]
}
```

![image](https://on.ahmda.ws/riqo/c)

Trying to create an Azure function.

Several errors in my terminal output:

```sh

> Executing task: func host start <


                  %%%%%%
                 %%%%%%
            @   %%%%%%    @
          @@   %%%%%%      @@
       @@@    %%%%%%%%%%%    @@@
     @@      %%%%%%%%%%        @@
       @@         %%%%       @@
         @@      %%%       @@
           @@    %%      @@
                %%
                %

Hosting environment: Production
Content root path: /Users/$USER/Documents/Web/Sandbox/afn
Now listening on: http://localhost:7071
Application started. Press Ctrl+C to shut down.
[5/19/18 8:24:57 PM] Reading host configuration file '/Users/$USER/Documents/Web/Sandbox/afn/host.json'
[5/19/18 8:24:57 PM] Host configuration file read:
[5/19/18 8:24:57 PM] {}
[5/19/18 8:24:57 PM] Starting Host (HostId=ahmadsmacbookpro-763423413, InstanceId=50434726-525b-4afa-9566-a137447a193f, Version=2.0.11651.0, ProcessId=98058, AppDomainId=1, Debug=False, ConsecutiveErrors=0, StartupCount=1, FunctionsExtensionVersion=)
[5/19/18 8:24:57 PM] Unable to configure java worker. Could not find JAVA_HOME app setting.
[5/19/18 8:24:57 PM]
[5/19/18 8:24:57 PM] Could not configure language worker Java.
[5/19/18 8:24:57 PM]
[5/19/18 8:24:57 PM] Start Process: node  --inspect=5858 "/usr/local/Cellar/azure-functions-core-tools/2.0.1-beta.25/workers/node/dist/src/nodejsWorker.js" --host 127.0.0.1 --port 55405 --workerId 33587250-9112-4a07-a373-8572a42396da --requestId 53993c42-bc16-4358-ab64-074a66876e11
[5/19/18 8:24:57 PM] Debugger listening on port 5858.
[5/19/18 8:24:57 PM] Warning: This is an experimental feature and could change at any time.
[5/19/18 8:24:57 PM] To start debugging, open the following URL in Chrome:
[5/19/18 8:24:57 PM]     chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:5858/a514a2fa-8b05-47f9-b371-79afd68b44c5
[5/19/18 8:24:57 PM] Generating 1 job function(s)
[5/19/18 8:24:57 PM] Found the following functions:
[5/19/18 8:24:57 PM] Host.Functions.HttpTriggerJS
[5/19/18 8:24:57 PM]
[5/19/18 8:24:57 PM] Host initialized (656ms)
[5/19/18 8:24:57 PM] azure-functions-nodejs-worker officially supports node version >=8.4.0. Current version v7.10.0.
[5/19/18 8:24:57 PM] To install required native modules for v7.10.0, install node-pre-gyp via 'npm i -g node-pre-gyp'.
[5/19/18 8:24:57 PM] Navigate to '<node-worker-dir>/grpc' and run 'node-pre-gyp install'
[5/19/18 8:24:57 PM] Host started (687ms)
[5/19/18 8:24:57 PM] Job host started
[5/19/18 8:24:57 PM] Couldn't require bundle, falling back to Worker.js. Error: Cannot find module '/usr/local/Cellar/azure-functions-core-tools/2.0.1-beta.25/workers/node/grpc/src/node/extension_binary/node-v51-darwin-x64/grpc_node.node'
[5/19/18 8:24:57 PM] module.js:472
[5/19/18 8:24:57 PM]     throw err;
[5/19/18 8:24:57 PM]     ^
[5/19/18 8:24:57 PM] Error: Cannot find module './Worker.js'
[5/19/18 8:24:57 PM]     at Function.Module._resolveFilename (module.js:470:15)
[5/19/18 8:24:57 PM]     at Function.Module._load (module.js:418:25)
[5/19/18 8:24:57 PM]     at Module.require (module.js:498:17)
[5/19/18 8:24:57 PM]     at require (internal/module.js:20:19)
[5/19/18 8:24:57 PM]     at Object.<anonymous> (/usr/local/Cellar/azure-functions-core-tools/2.0.1-beta.25/workers/node/dist/src/nodejsWorker.js:8:14)
[5/19/18 8:24:57 PM]     at Module._compile (module.js:571:32)
[5/19/18 8:24:57 PM]     at Object.Module._extensions..js (module.js:580:10)
[5/19/18 8:24:57 PM]     at Module.load (module.js:488:32)
[5/19/18 8:24:57 PM]     at tryModuleLoad (module.js:447:12)
[5/19/18 8:24:57 PM]     at Function.Module._load (module.js:439:3)
[5/19/18 8:24:57 PM] Worker encountered an error.
[5/19/18 8:24:57 PM] Worker process with pid 98060 exited with code 1.
[5/19/18 8:24:57 PM] Start Process: node  --inspect=5858 "/usr/local/Cellar/azure-functions-core-tools/2.0.1-beta.25/workers/node/dist/src/nodejsWorker.js" --host 127.0.0.1 --port 55405 --workerId fa3f45e4-eb03-424a-903f-e3e25ee692ad --requestId e3ec9f82-c612-4706-be84-aff784a88ff4
[5/19/18 8:24:57 PM] Debugger listening on port 5858.
[5/19/18 8:24:57 PM] Warning: This is an experimental feature and could change at any time.
[5/19/18 8:24:57 PM] To start debugging, open the following URL in Chrome:
[5/19/18 8:24:57 PM]     chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:5858/XXXXX-0e65-47d6-b569-63693636c245
Listening on http://localhost:7071/
Hit CTRL-C to exit...

Http Functions:

        HttpTriggerJS: http://localhost:7071/api/HttpTriggerJS

[5/19/18 8:24:57 PM] azure-functions-nodejs-worker officially supports node version >=8.4.0. Current version v7.10.0.
[5/19/18 8:24:57 PM] To install required native modules for v7.10.0, install node-pre-gyp via 'npm i -g node-pre-gyp'.
[5/19/18 8:24:57 PM] Navigate to '<node-worker-dir>/grpc' and run 'node-pre-gyp install'
[5/19/18 8:24:58 PM] Couldn't require bundle, falling back to Worker.js. Error: Cannot find module '/usr/local/Cellar/azure-functions-core-tools/2.0.1-beta.25/workers/node/grpc/src/node/extension_binary/node-v51-darwin-x64/grpc_node.node'
[5/19/18 8:24:58 PM] module.js:472
[5/19/18 8:24:58 PM]     throw err;
[5/19/18 8:24:58 PM]     ^
[5/19/18 8:24:58 PM] Error: Cannot find module './Worker.js'
[5/19/18 8:24:58 PM]     at Function.Module._resolveFilename (module.js:470:15)
[5/19/18 8:24:58 PM]     at Function.Module._load (module.js:418:25)
[5/19/18 8:24:58 PM]     at Module.require (module.js:498:17)
[5/19/18 8:24:58 PM]     at require (internal/module.js:20:19)
[5/19/18 8:24:58 PM]     at Object.<anonymous> (/usr/local/Cellar/azure-functions-core-tools/2.0.1-beta.25/workers/node/dist/src/nodejsWorker.js:8:14)
[5/19/18 8:24:58 PM]     at Module._compile (module.js:571:32)
[5/19/18 8:24:58 PM]     at Object.Module._extensions..js (module.js:580:10)
[5/19/18 8:24:58 PM]     at Module.load (module.js:488:32)
[5/19/18 8:24:58 PM]     at tryModuleLoad (module.js:447:12)
[5/19/18 8:24:58 PM]     at Function.Module._load (module.js:439:3)
[5/19/18 8:24:58 PM] Worker encountered an error.
[5/19/18 8:24:58 PM] Worker process with pid 98062 exited with code 1.
[5/19/18 8:24:58 PM] Start Process: node  --inspect=5858 "/usr/local/Cellar/azure-functions-core-tools/2.0.1-beta.25/workers/node/dist/src/nodejsWorker.js" --host 127.0.0.1 --port 55405 --workerId e50dd0da-8419-49b8-8a25-87520752a694 --requestId 71f7ab6c-a836-4d57-b0f8-8f9d541f6b4d
[5/19/18 8:24:58 PM] Debugger listening on port 5858.
[5/19/18 8:24:58 PM] Warning: This is an experimental feature and could change at any time.
[5/19/18 8:24:58 PM] To start debugging, open the following URL in Chrome:
[5/19/18 8:24:58 PM]     chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:5858/as-631d-4dfe-b7da-7e9ccf4379e9
[5/19/18 8:24:58 PM] azure-functions-nodejs-worker officially supports node version >=8.4.0. Current version v7.10.0.
[5/19/18 8:24:58 PM] To install required native modules for v7.10.0, install node-pre-gyp via 'npm i -g node-pre-gyp'.
[5/19/18 8:24:58 PM] Navigate to '<node-worker-dir>/grpc' and run 'node-pre-gyp install'
[5/19/18 8:24:58 PM] Couldn't require bundle, falling back to Worker.js. Error: Cannot find module '/usr/local/Cellar/azure-functions-core-tools/2.0.1-beta.25/workers/node/grpc/src/node/extension_binary/node-v51-darwin-x64/grpc_node.node'
[5/19/18 8:24:58 PM] module.js:472
[5/19/18 8:24:58 PM]     throw err;
[5/19/18 8:24:58 PM]     ^
[5/19/18 8:24:58 PM] Error: Cannot find module './Worker.js'
[5/19/18 8:24:58 PM]     at Function.Module._resolveFilename (module.js:470:15)
[5/19/18 8:24:58 PM]     at Function.Module._load (module.js:418:25)
[5/19/18 8:24:58 PM]     at Module.require (module.js:498:17)
[5/19/18 8:24:58 PM]     at require (internal/module.js:20:19)
[5/19/18 8:24:58 PM]     at Object.<anonymous> (/usr/local/Cellar/azure-functions-core-tools/2.0.1-beta.25/workers/node/dist/src/nodejsWorker.js:8:14)
[5/19/18 8:24:58 PM]     at Module._compile (module.js:571:32)
[5/19/18 8:24:58 PM]     at Object.Module._extensions..js (module.js:580:10)
[5/19/18 8:24:58 PM]     at Module.load (module.js:488:32)
[5/19/18 8:24:58 PM]     at tryModuleLoad (module.js:447:12)
[5/19/18 8:24:58 PM]     at Function.Module._load (module.js:439:3)
[5/19/18 8:24:58 PM] Worker encountered an error.
[5/19/18 8:24:58 PM] Worker process with pid 98063 exited with code 1.

```

Help.

**Comment by thesilverbadger** [comment]
I had the same issue, and it seems partially related to the Node version installed (I had v10). I believe the functions runtime only supports v8.

My functions now run at least, but I still get the debugger error

**Comment by ahmadawais** [comment]
@thesilverbadger that's right. I have v10 installed.

**Comment by apulliam** [comment]
I'm getting the same error with Node 8.11.2 and v2 runtime on Windows.  v1 runtime works fine as long as I set protocol to "legacy" in launch.json.  I can't connect the vscode debugger to v2 runtime using either "legacy" or "inspector" protocol.

**Comment by EricJizbaMSFT** [comment]
This only reproduces for me on the latest version of the func cli. As a workaround, you can install the previous version with this command:
```
npm i -g azure-functions-core-tools@2.0.1-beta.25
```

@ahmelsayed @fabiocav any idea why the .26 release would've broken javascript debugging in VS Code?

**Comment by fabiocav** [comment]
There were some changes with the Node worker in this release. 

@EricJizbaMSFT , I'm assuming you see the issue if Node 8.4.0 or higher is installed, is that correct?

/cc @mhoeger as she might have more information on the issue.

**Comment by thesilverbadger** [comment]
Can confirm that 2.0.1-beta.25 fixes the issue for me, running Node 8.11.2 and VS Code 1.23.1

**Comment by mhoeger** [comment]
It looks like this PR introduced a change in the way we check for debug port: https://github.com/Azure/azure-functions-host/commit/980107fb13e18f75be545948ede20933ea93a590. 

It seems like the issue may be more fundamental though, as adding the additional environment variable (see snippet below) which sets the --inspect param correctly does not attach a debugger correctly. 

`"options": {
                "env": {
                    "workers:node:debug": "5858"
                }
            }`

I'm filing an issue for this against the runtime, cc @pragnagopa

**Comment by EricJizbaMSFT** [comment]
Awesome thanks! @fabiocav just to be clear - when you say "we can have this patched" do you mean it would be backwards compatible with the old behavior?

I don't entirely follow the changes mentioned by @mhoeger, but it would be difficult for our extension to change existing 'launch.json' or 'tasks.json' files, especially since users might've already customized them. We can certainly update our templates if need be, but that only affects _new_ projects.

**Comment by fabiocav** [comment]
We'll discuss whether this would be fixed to be backwards compatible. It wouldn't be difficult to do that, but we only have a chance to make those kinds of changes while we're in preview, and keeping preview behavior for backwards compatibility is something we're trying to avoid. With that said, this wouldn't be problematic to keep, so I don't think it would be an issue.

**Comment by mhoeger** [comment]
Correction to my comment earlier: adding the following property to a task in tasks.json will correctly attach the debugger:
`"options": { "env": { "workers:node:debug": "5858" } }` 
(see https://github.com/Azure/azure-functions-host/issues/2878 for details).

@EricJizbaMSFT - we're still looking into being backwards compatible, although it might not be in the next release.

**Comment by passionkind** [comment]
This doesn't work for me :(

`launch.json`
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "attach",
      "name": "Attach by Process ID",
      "processId": "${command:PickProcess}"
    },
    {
      "name": "Attach to JavaScript Functions",
      "type": "node",
      "request": "attach",
      "port": 5858,
      "protocol": "inspector",
      "preLaunchTask": "runFunctionsHost",
    }
  ]
}
```

`tasks.json`
```
{
  "version": "2.0.0",
  "tasks": [
    {
      "options": {
        "cwd": "dist",
        "env": {
          "workers:node:debug": "5858"
        }
      },
      "label": "Run Functions Host",
      "identifier": "runFunctionsHost",
      "type": "shell",
      "command": "func host start",
      "isBackground": true,
      "presentation": {
        "reveal": "always"
      },
      "problemMatcher": [
        {
          "owner": "azureFunctions",
          "pattern": [
            {
              "regexp": "\\b\\B",
              "file": 1,
              "location": 2,
              "message": 3
            }
          ],
          "background": {
            "activeOnStart": true,
            "beginsPattern": "^.*Stopping host.*",
            "endsPattern": "^.*Job host started.*"
          }
        }
      ]
    }
  ]
}
```

Note: using `Attach by Process ID` to manually attach the debugger works. But it does not connect automatically when the task is launching. This would be very helpful for code reload on change.

**Comment by EricJizbaMSFT** [comment]
@mhoeger The 'env' option you described is also not working for me.

**Comment by fabiocav** [comment]
**NOTE:** When running on a non-Windows machine, the environment name should be `workers__node__Debug`. This is case sensitive, so the capital `D` is important.

**Comment by jdneo** [comment]
Same issue in Java. It looks like the function cli does not start the JVM in debug mode.

**Comment by passionkind** [comment]
I can confirm that setting `workers__node__Debug` instead of `workers:node:debug` works like a charm. Thank you @fabiocav and @mhoeger 

Is this a general convention between windows and non-windows operation systems? I once wondered why typescript `@types` usually convert subsequent slashes into double underscores. Does this somehow relate with each other?

**Comment by EricJizbaMSFT** [comment]
Closing this issue as it has been fixed in the latest version of the func cli. The workarounds mentioned above are no longer necessary - simply update your func cli:
```
npm i -g azure-functions-core-tools@core
```

or

```
brew upgrade azure-functions-core-tools
```

**Comment by ahmadawais** [comment]
@EricJizbaMSFT I can confirm that it's still not working for me on MacOS. :(

I ran 

```sh
brew upgrade azure-functions-core-tools
```

OUTPUT

```sh
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
No changes to formulae.

Error: azure/functions/azure-functions-core-tools 2.0.1-beta.28 already installed
```

When I create an Azure function, let's say HTTP triggered JavaScript based function. And press play in the debug the following is what I get as output in my terminal.

<details>
 <summary>TERMINAL OUTPUT (CLICK TO EXPAND!)</summary>


```sh

> Executing task: func host start <


                  %%%%%%
                 %%%%%%
            @   %%%%%%    @
          @@   %%%%%%      @@
       @@@    %%%%%%%%%%%    @@@
     @@      %%%%%%%%%%        @@
       @@         %%%%       @@
         @@      %%%       @@
           @@    %%      @@
                %%
                %

Hosting environment: Production
Content root path: /Users/ahmadawais/Documents/Web/Sandbox/demo-azure-func
Now listening on: http://localhost:7071
Application started. Press Ctrl+C to shut down.
[5/31/18 11:58:20 PM] Reading host configuration file '/Users/ahmadawais/Documents/Web/Sandbox/demo-azure-func/host.json'
[5/31/18 11:58:20 PM] Host configuration file read:
[5/31/18 11:58:20 PM] {}
[5/31/18 11:58:20 PM] Starting Host (HostId=ahmadsmacbookpro-1530556110, InstanceId=2485c474-9ed2-4041-b716-b11e819adb18, Version=2.0.11776.0, ProcessId=60925, AppDomainId=1, Debug=False, ConsecutiveErrors=0, StartupCount=1, FunctionsExtensionVersion=)
[5/31/18 11:58:20 PM] Loading all the worker providers from the default workers directory: /usr/local/Cellar/azure-functions-core-tools/2.0.1-beta.28/workers
[5/31/18 11:58:20 PM] Found worker config: /usr/local/Cellar/azure-functions-core-tools/2.0.1-beta.28/workers/python/worker.config.json
[5/31/18 11:58:20 PM] Will load worker provider for language: python
[5/31/18 11:58:20 PM] Start Process: node  --inspect=5858 "/usr/local/Cellar/azure-functions-core-tools/2.0.1-beta.28/workers/node/dist/src/nodejsWorker.js" --host 127.0.0.1 --port 64239 --workerId eb429ee4-d00a-4aa9-8ea1-3b9b62facfb0 --requestId 7bd13f1f-4b9b-478f-89ca-61e32683718d --grpcMaxMessageLength 134217728
[5/31/18 11:58:20 PM] Generating 1 job function(s)
[5/31/18 11:58:20 PM] Found the following functions:
[5/31/18 11:58:20 PM] Host.Functions.HttpTriggerJS
[5/31/18 11:58:20 PM]
[5/31/18 11:58:20 PM] Host initialized (834ms)
[5/31/18 11:58:20 PM] Host started (881ms)
[5/31/18 11:58:20 PM] Job host started
[5/31/18 11:58:20 PM] Debugger listening on port 5858.
[5/31/18 11:58:20 PM] Warning: This is an experimental feature and could change at any time.
[5/31/18 11:58:20 PM] To start debugging, open the following URL in Chrome:
[5/31/18 11:58:20 PM]     chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:5858/38025454-03f3-4ff6-a096-f10c16bf46da
Listening on http://localhost:7071/
Hit CTRL-C to exit...

Http Functions:

        HttpTriggerJS: http://localhost:7071/api/HttpTriggerJS

[5/31/18 11:58:21 PM] azure-functions-nodejs-worker officially supports node version >=8.4.0. Current version v7.10.0.
[5/31/18 11:58:21 PM] To install required native modules for v7.10.0, install node-pre-gyp via 'npm i -g node-pre-gyp'.
[5/31/18 11:58:21 PM] Navigate to '<node-worker-dir>/grpc' and run 'node-pre-gyp install'
[5/31/18 11:58:21 PM] Couldn't require bundle, falling back to Worker.js. Error: Cannot find module '/usr/local/Cellar/azure-functions-core-tools/2.0.1-beta.28/workers/node/grpc/src/node/extension_binary/node-v51-darwin-x64/grpc_node.node'
[5/31/18 11:58:21 PM] module.js:472
[5/31/18 11:58:21 PM]     throw err;
[5/31/18 11:58:21 PM]     ^
[5/31/18 11:58:21 PM] Error: Cannot find module './Worker.js'
[5/31/18 11:58:21 PM]     at Function.Module._resolveFilename (module.js:470:15)
[5/31/18 11:58:21 PM]     at Function.Module._load (module.js:418:25)
[5/31/18 11:58:21 PM]     at Module.require (module.js:498:17)
[5/31/18 11:58:21 PM]     at require (internal/module.js:20:19)
[5/31/18 11:58:21 PM]     at Object.<anonymous> (/usr/local/Cellar/azure-functions-core-tools/2.0.1-beta.28/workers/node/dist/src/nodejsWorker.js:8:14)
[5/31/18 11:58:21 PM]     at Module._compile (module.js:571:32)
[5/31/18 11:58:21 PM]     at Object.Module._extensions..js (module.js:580:10)
[5/31/18 11:58:21 PM]     at Module.load (module.js:488:32)
[5/31/18 11:58:21 PM]     at tryModuleLoad (module.js:447:12)
[5/31/18 11:58:21 PM]     at Function.Module._load (module.js:439:3)
[5/31/18 11:58:21 PM] Worker encountered an error.
[5/31/18 11:58:21 PM] Worker process with pid 60936 exited with code 1.
[5/31/18 11:58:21 PM] Start Process: node  --inspect=5858 "/usr/local/Cellar/azure-functions-core-tools/2.0.1-beta.28/workers/node/dist/src/nodejsWorker.js" --host 127.0.0.1 --port 64239 --workerId 13d9c4eb-ef83-4269-a3a4-96c2d21d36f7 --requestId e1d8dc1b-f79c-49f6-af53-0f06131750b1 --grpcMaxMessageLength 134217728
[5/31/18 11:58:21 PM] Debugger listening on port 5858.
[5/31/18 11:58:21 PM] Warning: This is an experimental feature and could change at any time.
[5/31/18 11:58:21 PM] To start debugging, open the following URL in Chrome:
[5/31/18 11:58:21 PM]     chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:5858/404b2994-7fe4-482c-a4d9-47b162c9c016
[5/31/18 11:58:21 PM] azure-functions-nodejs-worker officially supports node version >=8.4.0. Current version v7.10.0.
[5/31/18 11:58:21 PM] To install required native modules for v7.10.0, install node-pre-gyp via 'npm i -g node-pre-gyp'.
[5/31/18 11:58:21 PM] Navigate to '<node-worker-dir>/grpc' and run 'node-pre-gyp install'
[5/31/18 11:58:21 PM] Couldn't require bundle, falling back to Worker.js. Error: Cannot find module '/usr/local/Cellar/azure-functions-core-tools/2.0.1-beta.28/workers/node/grpc/src/node/extension_binary/node-v51-darwin-x64/grpc_node.node'
[5/31/18 11:58:21 PM] module.js:472
[5/31/18 11:58:21 PM]     throw err;
[5/31/18 11:58:21 PM]     ^
[5/31/18 11:58:21 PM] Error: Cannot find module './Worker.js'
[5/31/18 11:58:21 PM]     at Function.Module._resolveFilename (module.js:470:15)
[5/31/18 11:58:21 PM]     at Function.Module._load (module.js:418:25)
[5/31/18 11:58:21 PM]     at Module.require (module.js:498:17)
[5/31/18 11:58:21 PM]     at require (internal/module.js:20:19)
[5/31/18 11:58:21 PM]     at Object.<anonymous> (/usr/local/Cellar/azure-functions-core-tools/2.0.1-beta.28/workers/node/dist/src/nodejsWorker.js:8:14)
[5/31/18 11:58:21 PM]     at Module._compile (module.js:571:32)
[5/31/18 11:58:21 PM]     at Object.Module._extensions..js (module.js:580:10)
[5/31/18 11:58:21 PM]     at Module.load (module.js:488:32)
[5/31/18 11:58:21 PM]     at tryModuleLoad (module.js:447:12)
[5/31/18 11:58:21 PM]     at Function.Module._load (module.js:439:3)
[5/31/18 11:58:21 PM] Worker encountered an error.
[5/31/18 11:58:21 PM] Worker process with pid 60938 exited with code 1.
[5/31/18 11:58:21 PM] Start Process: node  --inspect=5858 "/usr/local/Cellar/azure-functions-core-tools/2.0.1-beta.28/workers/node/dist/src/nodejsWorker.js" --host 127.0.0.1 --port 64239 --workerId 730f8528-4b09-4340-8d85-4f3e67a7b033 --requestId cbc03b01-628f-436c-bf82-3eafd59fd699 --grpcMaxMessageLength 134217728
[5/31/18 11:58:21 PM] Debugger listening on port 5858.
[5/31/18 11:58:21 PM] Warning: This is an experimental feature and could change at any time.
[5/31/18 11:58:21 PM] To start debugging, open the following URL in Chrome:
[5/31/18 11:58:21 PM]     chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:5858/ccb6f279-c7d1-4bfe-a13a-49f79db2dbf7
[5/31/18 11:58:21 PM] azure-functions-nodejs-worker officially supports node version >=8.4.0. Current version v7.10.0.
[5/31/18 11:58:21 PM] To install required native modules for v7.10.0, install node-pre-gyp via 'npm i -g node-pre-gyp'.
[5/31/18 11:58:21 PM] Navigate to '<node-worker-dir>/grpc' and run 'node-pre-gyp install'
[5/31/18 11:58:21 PM] Couldn't require bundle, falling back to Worker.js. Error: Cannot find module '/usr/local/Cellar/azure-functions-core-tools/2.0.1-beta.28/workers/node/grpc/src/node/extension_binary/node-v51-darwin-x64/grpc_node.node'
[5/31/18 11:58:21 PM] module.js:472
[5/31/18 11:58:21 PM]     throw err;
[5/31/18 11:58:21 PM]     ^
[5/31/18 11:58:21 PM] Error: Cannot find module './Worker.js'
[5/31/18 11:58:21 PM]     at Function.Module._resolveFilename (module.js:470:15)
[5/31/18 11:58:21 PM]     at Function.Module._load (module.js:418:25)
[5/31/18 11:58:21 PM]     at Module.require (module.js:498:17)
[5/31/18 11:58:21 PM]     at require (internal/module.js:20:19)
[5/31/18 11:58:21 PM]     at Object.<anonymous> (/usr/local/Cellar/azure-functions-core-tools/2.0.1-beta.28/workers/node/dist/src/nodejsWorker.js:8:14)
[5/31/18 11:58:21 PM]     at Module._compile (module.js:571:32)
[5/31/18 11:58:21 PM]     at Object.Module._extensions..js (module.js:580:10)
[5/31/18 11:58:21 PM]     at Module.load (module.js:488:32)
[5/31/18 11:58:21 PM]     at tryModuleLoad (module.js:447:12)
[5/31/18 11:58:21 PM]     at Function.Module._load (module.js:439:3)
[5/31/18 11:58:21 PM] Worker encountered an error.
[5/31/18 11:58:21 PM] Worker process with pid 60939 exited with code 1.Details!


```

</details>


And the same error 

![image](https://on.ahmda.ws/rzs1/as)	

Help.

**Comment by ahmadawais** [comment]
@mhoeger I tried what you suggested along with @fabiocav but stil nothing. Same errors.

**Comment by EricJizbaMSFT** [comment]
@ahmadawais I think this is the key part of the log for you:
```
azure-functions-nodejs-worker officially supports node version >=8.4.0. Current version v7.10.0.
[5/31/18 11:58:21 PM] To install required native modules for v7.10.0, install node-pre-gyp via 'npm i -g node-pre-gyp'.
[5/31/18 11:58:21 PM] Navigate to '<node-worker-dir>/grpc' and run 'node-pre-gyp install'
```

I would recommend updating your version of Node, but if you need to stick to v7.10.0 then you can follow the instructions to 'install required native modules'

**Comment by ahmadawais** [comment]
@EricJizbaMSFT That's the thing. As you can check from the first comment in this issue I am using Node v10 locally.

```sh
VSCode 1.23.1
MacOS 
Node: 10.1.0
OS: macOS Sierra
npm: 6.0.1
Chrome: 66.0.3359.181
```

I have also tried with Node 9.7.1 and this message is beyond me I don't know why I am getting this error. Any help?

**Comment by EricJizbaMSFT** [comment]
Do you see v10 when you run `node --version` from the command prompt? Is it set correctly on your PATH?
<img width="327" alt="screen shot 2018-06-01 at 9 16 31 am" src="https://user-images.githubusercontent.com/11282622/40851541-92beaeca-657c-11e8-9a74-0d7e4433ef44.png">

**Comment by pragnagopa** [comment]
@ahmadawais - This issue was tracking broken debug experience from VSCode, which is now fixed in the latest version of CLI 2.0.1-beta.28. The issue you running into might be due to node version. Can you please open a new issue in https://github.com/Azure/azure-functions-nodejs-worker repo?

**Comment by ahmadawais** [comment]
Yes I do see that. Also I switched to v9.7.1 but no luck. It's correctly in
thr $PATH ... I am a Node.js dev just in case you know. Also I use nvm for
different nide version management.

**Comment by EricJizbaMSFT** [comment]
@ahmadawais I'll echo what @pragnagopa said. There were two issues here - one directly related to VS Code (which was fixed) and one specific to the azure-functions-nodejs-worker. I don't think there's anything we could do from the VS Code side to fix your issue and I recommend investigating it further in the repo she mentioned: https://github.com/Azure/azure-functions-nodejs-worker

**Comment by ahmadawais** [comment]
Sure done https://github.com/Azure/azure-functions-nodejs-worker/issues/89

**Comment by ahmadawais** [comment]
@mikeclymer thanks for the update but I have had tried this before and I just tried it again. Didn't work. This is the ouput now.

```sh
> Executing task: func host start <


                  %%%%%%
                 %%%%%%
            @   %%%%%%    @
          @@   %%%%%%      @@
       @@@    %%%%%%%%%%%    @@@
     @@      %%%%%%%%%%        @@
       @@         %%%%       @@
         @@      %%%       @@
           @@    %%      @@
                %%
                %

Hosting environment: Production
Content root path: /Users/ahmadawais/Documents/Web/Sandbox/demoazurefunc
Now listening on: http://localhost:7071
Application started. Press Ctrl+C to shut down.
[6/8/18 10:00:23 PM] Reading host configuration file '/Users/ahmadawais/Documents/Web/Sandbox/demoazurefunc/host.json'
[6/8/18 10:00:23 PM] Host configuration file read:
[6/8/18 10:00:23 PM] {}
[6/8/18 10:00:23 PM] Starting Host (HostId=ahmadsmacbookpro-552755506, InstanceId=57b3f52e-2e98-4014-b96c-a7b0b191533f, Version=2.0.11776.0, ProcessId=67768, AppDomainId=1, Debug=False, ConsecutiveErrors=0, StartupCount=1, FunctionsExtensionVersion=)
[6/8/18 10:00:24 PM] Loading all the worker providers from the default workers directory: /usr/local/Cellar/azure-functions-core-tools/2.0.1-beta.28/workers
[6/8/18 10:00:24 PM] Found worker config: /usr/local/Cellar/azure-functions-core-tools/2.0.1-beta.28/workers/python/worker.config.json
[6/8/18 10:00:24 PM] Will load worker provider for language: python
[6/8/18 10:00:24 PM] Start Process: node  --inspect=5858 "/usr/local/Cellar/azure-functions-core-tools/2.0.1-beta.28/workers/node/dist/src/nodejsWorker.js" --host 127.0.0.1 --port 59035 --workerId 2dfd6191-c937-434b-b534-00aeec4ac846 --requestId 3249c043-f995-43ba-bf3e-5e6d0750ecce --grpcMaxMessageLength 134217728
[6/8/18 10:00:24 PM] Debugger listening on ws://127.0.0.1:5858/38b6875c-cf13-4828-9709-a4bd3ae00629
[6/8/18 10:00:24 PM] For help, see: https://nodejs.org/en/docs/inspector
[6/8/18 10:00:24 PM] Generating 1 job function(s)
[6/8/18 10:00:24 PM] Found the following functions:
[6/8/18 10:00:24 PM] Host.Functions.HttpTriggerJS
[6/8/18 10:00:24 PM]
[6/8/18 10:00:24 PM] Host initialized (829ms)
[6/8/18 10:00:24 PM] Couldn't require bundle, falling back to Worker.js. Error: Cannot find module '/usr/local/Cellar/azure-functions-core-tools/2.0.1-beta.28/workers/node/grpc/src/node/extension_binary/node-v64-darwin-x64/grpc_node.node'
[6/8/18 10:00:24 PM] internal/modules/cjs/loader.js:573
[6/8/18 10:00:24 PM]     throw err;
[6/8/18 10:00:24 PM]     ^
[6/8/18 10:00:24 PM] Error: Cannot find module './Worker.js'
[6/8/18 10:00:24 PM]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
[6/8/18 10:00:24 PM]     at Function.Module._load (internal/modules/cjs/loader.js:497:25)
[6/8/18 10:00:24 PM]     at Module.require (internal/modules/cjs/loader.js:626:17)
[6/8/18 10:00:24 PM]     at require (internal/modules/cjs/helpers.js:20:18)
[6/8/18 10:00:24 PM]     at Object.<anonymous> (/usr/local/Cellar/azure-functions-core-tools/2.0.1-beta.28/workers/node/dist/src/nodejsWorker.js:8:14)
[6/8/18 10:00:24 PM]     at Module._compile (internal/modules/cjs/loader.js:678:30)
[6/8/18 10:00:24 PM]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
[6/8/18 10:00:24 PM]     at Module.load (internal/modules/cjs/loader.js:589:32)
[6/8/18 10:00:24 PM]     at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
[6/8/18 10:00:24 PM]     at Function.Module._load (internal/modules/cjs/loader.js:520:3)
[6/8/18 10:00:24 PM] Host started (880ms)
[6/8/18 10:00:24 PM] Job host started
Listening on http://localhost:7071/
Hit CTRL-C to exit...

Http Functions:

        HttpTriggerJS: http://localhost:7071/api/HttpTriggerJS

[6/8/18 10:00:24 PM] Worker encountered an error.
[6/8/18 10:00:24 PM] Worker process with pid 67778 exited with code 1.
[6/8/18 10:00:24 PM] Start Process: node  --inspect=5858 "/usr/local/Cellar/azure-functions-core-tools/2.0.1-beta.28/workers/node/dist/src/nodejsWorker.js" --host 127.0.0.1 --port 59035 --workerId 2a29965b-a6a3-44c5-8299-338ae5f11b6c --requestId f12448a6-ed27-4d58-bfad-e7388aa55cc6 --grpcMaxMessageLength 134217728
[6/8/18 10:00:24 PM] Debugger listening on ws://127.0.0.1:5858/1ac024e1-2b4c-4c68-b967-bcad8b886729
[6/8/18 10:00:24 PM] For help, see: https://nodejs.org/en/docs/inspector
[6/8/18 10:00:24 PM] Couldn't require bundle, falling back to Worker.js. Error: Cannot find module '/usr/local/Cellar/azure-functions-core-tools/2.0.1-beta.28/workers/node/grpc/src/node/extension_binary/node-v64-darwin-x64/grpc_node.node'
[6/8/18 10:00:24 PM] internal/modules/cjs/loader.js:573
[6/8/18 10:00:24 PM]     throw err;
[6/8/18 10:00:24 PM]     ^
[6/8/18 10:00:24 PM] Error: Cannot find module './Worker.js'
[6/8/18 10:00:24 PM]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
[6/8/18 10:00:24 PM]     at Function.Module._load (internal/modules/cjs/loader.js:497:25)
[6/8/18 10:00:24 PM]     at Module.require (internal/modules/cjs/loader.js:626:17)
[6/8/18 10:00:24 PM]     at require (internal/modules/cjs/helpers.js:20:18)
[6/8/18 10:00:24 PM]     at Object.<anonymous> (/usr/local/Cellar/azure-functions-core-tools/2.0.1-beta.28/workers/node/dist/src/nodejsWorker.js:8:14)
[6/8/18 10:00:24 PM]     at Module._compile (internal/modules/cjs/loader.js:678:30)
[6/8/18 10:00:24 PM]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
[6/8/18 10:00:24 PM]     at Module.load (internal/modules/cjs/loader.js:589:32)
[6/8/18 10:00:24 PM]     at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
[6/8/18 10:00:24 PM]     at Function.Module._load (internal/modules/cjs/loader.js:520:3)
[6/8/18 10:00:24 PM] Worker encountered an error.
[6/8/18 10:00:24 PM] Worker process with pid 67781 exited with code 1.
[6/8/18 10:00:24 PM] Start Process: node  --inspect=5858 "/usr/local/Cellar/azure-functions-core-tools/2.0.1-beta.28/workers/node/dist/src/nodejsWorker.js" --host 127.0.0.1 --port 59035 --workerId 459cf8d4-6780-4097-b860-5acc0d5f2784 --requestId c4d945b8-c07a-4f09-a86c-5f803f594803 --grpcMaxMessageLength 134217728
[6/8/18 10:00:24 PM] Debugger listening on ws://127.0.0.1:5858/66a5bdb5-aff1-456e-bd13-f2e487008cc4
[6/8/18 10:00:24 PM] For help, see: https://nodejs.org/en/docs/inspector
[6/8/18 10:00:25 PM] Debugger attached.
[6/8/18 10:00:25 PM] Couldn't require bundle, falling back to Worker.js. Error: Cannot find module '/usr/local/Cellar/azure-functions-core-tools/2.0.1-beta.28/workers/node/grpc/src/node/extension_binary/node-v64-darwin-x64/grpc_node.node'
[6/8/18 10:00:25 PM] internal/modules/cjs/loader.js:573
[6/8/18 10:00:25 PM]     throw err;
[6/8/18 10:00:25 PM]     ^
[6/8/18 10:00:25 PM] Error: Cannot find module './Worker.js'
[6/8/18 10:00:25 PM]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
[6/8/18 10:00:25 PM]     at Function.Module._load (internal/modules/cjs/loader.js:497:25)
[6/8/18 10:00:25 PM]     at Module.require (internal/modules/cjs/loader.js:626:17)
[6/8/18 10:00:25 PM]     at require (internal/modules/cjs/helpers.js:20:18)
[6/8/18 10:00:25 PM]     at Object.<anonymous> (/usr/local/Cellar/azure-functions-core-tools/2.0.1-beta.28/workers/node/dist/src/nodejsWorker.js:8:14)
[6/8/18 10:00:25 PM]     at Module._compile (internal/modules/cjs/loader.js:678:30)
[6/8/18 10:00:25 PM]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
[6/8/18 10:00:25 PM]     at Module.load (internal/modules/cjs/loader.js:589:32)
[6/8/18 10:00:25 PM]     at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
[6/8/18 10:00:25 PM]     at Function.Module._load (internal/modules/cjs/loader.js:520:3)
[6/8/18 10:00:25 PM] Waiting for the debugger to disconnect...
[6/8/18 10:00:25 PM] Worker encountered an error.
[6/8/18 10:00:25 PM] Worker process with pid 67782 exited with code 1.
```

**Comment by EricJizbaMSFT** [comment]
@mikeclymer thanks for the help. In terms of this:
> would making the runtimeExecutable attribute available for request types of attach be feasible? I would much rather set that in the config than muck with my nvm default.

You might be able to use environment variables in your launch.json to get this same effect, but please file a separate issue if you're still interested and we can investigate further

**Comment by markheath** [comment]
I am running into this same issue `Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:5858` on Windows 10, with Azure Functions Core Tools (2.0.1-beta.31) and node v10.7.0.

I am able to debug if I manually attach to the node process, but any reason why it's not working for me even though I have the latest tools installed?

**Comment by markheath** [comment]
@EricJizbaMSFT magic! that did the trick. Thanks for the speedy response.
