### ISSUE TITLE
Fail to delete the function in a function app which created with Flex Consumption (Preview) hosting plan

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#4066]
**OS:** All
**Build Version:** v1.14.1-alpha.0
**Regression:** Not a Regression

**Repro Steps:**
1. Create a python project with Http Trigger function.
2. Create a python function app with Flex Consumption (Preview) hosting plan and East US 2 EUAP location.
3. Deploy the python project to the above function app.
4. Expand the above function app -> Expand the "Functions" node -> Right click the function and execute "Delete Function..." action.
5. Check whether succeeds to delete the function.

**Expect:**
Succeed to delete the function.

**Actual:**
Fail to delete the function with an error.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/45614674/fa4caa08-0082-4d67-8354-a69eff8c691f)

**More Info:**
Another error occurs when deleting the function for the same function app in portal.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/45614674/6fb70147-5043-489d-9e38-90235b2144d2)

**Comment by nturinski** [comment]
Similar to https://github.com/microsoft/vscode-azurefunctions/issues/4067, might be a different endpoint now.

**Comment by nturinski** [comment]
I believe that this is fixed. Could it be reverified?

**Comment by v-ruizh** [comment]
Verified

> I believe that this is fixed. Could it be reverified?

Verified this bug on the latest main branch Functions extension build, this bug still reproduces.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/45614674/4c14ea34-824e-415d-a5bf-60af1625427d)
