### ISSUE TITLE
Fail to deploy the JavaScript/TypeScript project in regular function app

### ISSUE THREAD

**Issue by Amar-QA** [microsoft/vscode-azurefunctions#4071]
OS: All
Build Version: 20240401.1
Regression: It's a regression from **Previous Release v1.14.0**

**Repro Steps:** 

1. Create JavaScript/TypeScript project.
2. Create a Function App.
3. Right Click the Function App -> Select "Deploy to Function App" -> Click "Deploy Anyway" button.
4. Check whether succeeds to deploy to the function app.

**Expect:** 
Succeed to deploy the function app.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/156269329/a398c066-2483-4aab-a557-b2147a125ea1)

**Actual:** 
Fail to deploy the function app.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/156269329/e25c4d7f-65fa-424d-b93d-44da544b50af)
![image](https://github.com/microsoft/vscode-azurefunctions/assets/156269329/3b682628-6e6d-47bc-a3ee-cb3b5814cd6f)

**More info:** 

1. When verifying the function extension version under application settings, it has been stated as ~1 instead of ~4.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/156269329/21a7b3df-205a-45f5-8805-d2a5a4b3b85f)

**Comment by nturinski** [comment]
Thanks for finding this. This is an external issue with the controller. Will leave open for tracking.

**Comment by nturinski** [comment]
This should have been fixed by the service. Could you please reconfirm the bug?

**Comment by v-ruizh** [comment]
This issue does not reproduce for the function app with "Consumption/Premium/App Service Plan" hosting plan now.
But it still reproduces for function app with Flex Consumption (Preview) hosting plan.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/45614674/c640cd55-8d3f-4a63-afc3-df47a021f9e0)
