### ISSUE TITLE
MSB1003: Specify a project or solution file

### ISSUE THREAD

**Issue by veuncent** [Microsoft/vscode-azurefunctions#697]
I followed the step-by-step in Azure Portal when creating a new Azure Function using VSC.

At the local debugging step when hitting F5, I get the following error:
```
MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
The terminal process terminated with exit code: 1
```

Repro steps:
Follow the steps as detailed in the Azure Portal when creating a Function for the first time:
- Install VCO extensions: Azure Functions and C#
- Create a new function
- Hit f5

Additional info (autogenerated):
```
Action: azureFunctions.pickProcess
Error type: Error
Error Message: Failed to start debugging. Task "clean" failed with exit code "1".

Version: 0.11.0
OS: win32
```

**Comment by nturinski** [comment]
Hi @veuncent,

Sorry that you're running into problems with the extension.  

Did you create a Functions project before creating a new function?  When creating a function, you'll be prompted to select the folder that will contain the function.  It seems like you don't have a .csproj file should be generated when you press F5.

Thanks.  Hope we'll get you up and running soon!

**Comment by veuncent** [comment]
Thanks for your reply @nturinski 

I did create a project before I created the function and the .csproj is also present. 
Here is my code: https://github.com/globaldigitalheritage/azure-function-extract/tree/13b093d1e472d6e6a995ecccb3dc0be51990d17c

If I go to the root of that folder and manually run `dotnet clean` and `dotnet build` it runs without errors:
```
PS C:\Users\meije\Documents\Repositories\azure-function-extract> dotnet clean
Microsoft (R) Build Engine version 15.7.177.53362 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\Users\meije\Documents\Repositories\azure-function-extract> dotnet build
Microsoft (R) Build Engine version 15.7.177.53362 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 55.44 ms for C:\Users\meije\Documents\Repositories\azure-function-extract\azure-function-extract.csproj.
  azure-function-extract -> C:\Users\meije\Documents\Repositories\azure-function-extract\bin\Debug\netstandard2.0\bin\azure-function-extract.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:06.73
```


Thanks!

**Comment by veuncent** [comment]
My launch.json:
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Attach to C# Functions",
      "type": "coreclr",
      "request": "attach",
      "processId": "${command:azureFunctions.pickProcess}"
    }
  ]
}
```

**Comment by nturinski** [comment]
@veuncent, the launch file seems good, but do you have this task.json?
```
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "clean",
      "command": "dotnet clean",
      "type": "shell",
      "presentation": {
        "reveal": "always"
      },
      "problemMatcher": "$msCompile"
    },
    {
      "label": "build",
      "command": "dotnet build",
      "type": "shell",
      "dependsOn": "clean",
      "group": {
        "kind": "build",
        "isDefault": true
      },
      "presentation": {
        "reveal": "always"
      },
      "problemMatcher": "$msCompile"
    },
    {
      "label": "clean release",
      "command": "dotnet clean --configuration Release",
      "type": "shell",
      "presentation": {
        "reveal": "always"
      },
      "problemMatcher": "$msCompile"
    },
    {
      "label": "publish",
      "command": "dotnet publish --configuration Release",
      "type": "shell",
      "dependsOn": "clean release",
      "presentation": {
        "reveal": "always"
      },
      "problemMatcher": "$msCompile"
    },
    {
      "label": "runFunctionsHost",
      "type": "shell",
      "dependsOn": "build",
      "options": {
        "cwd": "${workspaceFolder}/bin/Debug/netstandard2.0"
      },
      "command": "func host start",
      "isBackground": true,
      "presentation": {
        "reveal": "always"
      },
      "problemMatcher": "$func-watch"
    }
  ]
}
```

I cloned your repo and recreated the project (via `Create New Project`) whcih generated the appropriate tasks.json, settings.json, and launch.json.

**Comment by veuncent** [comment]
I do have the task.json as well:
```
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "clean",
      "command": "dotnet clean",
      "type": "shell",
      "presentation": {
        "reveal": "always"
      },
      "problemMatcher": "$msCompile"
    },
    {
      "label": "build",
      "command": "dotnet build",
      "type": "shell",
      "dependsOn": "clean",
      "group": {
        "kind": "build",
        "isDefault": true
      },
      "presentation": {
        "reveal": "always"
      },
      "problemMatcher": "$msCompile"
    },
    {
      "label": "clean release",
      "command": "dotnet clean --configuration Release",
      "type": "shell",
      "presentation": {
        "reveal": "always"
      },
      "problemMatcher": "$msCompile"
    },
    {
      "label": "publish",
      "identifier": "publish",
      "command": "dotnet publish --configuration Release",
      "type": "shell",
      "dependsOn": "clean release",
      "presentation": {
        "reveal": "always"
      },
      "problemMatcher": "$msCompile"
    },
    {
      "label": "Run Functions Host",
      "identifier": "runFunctionsHost",
      "type": "shell",
      "dependsOn": "build",
      "options": {
        "cwd": "${workspaceFolder}/bin/Debug/netstandard2.0"
      },
      "command": "func host start",
      "isBackground": true,
      "presentation": {
        "reveal": "always"
      },
      "problemMatcher": "$func-watch"
    }
  ]
}
```

Here is a screenshot of my workspace:
![image](https://user-images.githubusercontent.com/7893339/46786818-4b4bff80-cd36-11e8-901b-7e3810ca6175.png)

**Comment by jinglouMSFT** [comment]
We just released a new version of the Functions extension, v0.12.0.  I tried to follow the "Create your first function using Visual Studio Code" tutorial using the new extension, I didn't seem to run into the issue you were seeing. I couldn't repro it either with the 0.11.0 release however.  This is what I did. Let us know if your steps were different.

1. start VS Code and select the Azure icon on the Activity bar.  In Functions' explorer, select the "folder" icon to create a new project. Select a location and folder to create the project.  If you don't have a folder already, create a new one in the "Select Folder" dialog. 
2. In the command palette, select C# for "Select a language for your function project"
3. In the command palette, select Add to workspace for "Select how you would like to open your project". This step is missing in the tutorial.  I've entered a bug to fix it. 
4. You might be prompted to resolve C# dependencies.  Please click the Restore button to continue setting up the C# dependencies. 
5. In the Functions explorer, select the lightening icon to create a Function.  
6. In the command palette, chose your project folder created in step 1 above when asked for the project folder
7. Select HttpTrigger for "Select a function template"
8. Give a function name for "Provide a function name (Press 'Enter' to confirm or 'Escape' to cancel)
9. Confirm for "Provide a namespace (Press 'Enter' to confirm or 'Escape' to cancel)
10. AccessRights could be Anonymous (which was what I used)

You should be good to go with F5.  Let us know if you still get any build error.  Thanks.

**Comment by patridge** [comment]
I just hit the same issue using v0.12.0 that I just installed today. I was following along with the [**Create your first function using Visual Studio Code**](https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-function-vs-code) docs. The error was similar for both JavaScript and C# projects, and the command it runs for both seems to have a weird `<` character I wasn't expecting that could be causing the issue.

Here's a section from the Task Terminal log after creating and trying to run a JS and then a C# Functions project.

```log
> Executing task: func extensions install <

Unable to find project root. Expecting to find one of host.json, local.settings.json in project root.
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.

> Executing task: dotnet clean <

Microsoft (R) Build Engine version 15.7.179.6572 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.
```

As mentioned by @veuncent, if I run `dotnet clean` and `dotnet build` in a PowerShell Terminal window in VS Code, they both run successfully. I also successfully ran `func host start` from the Terminal window.

It may be a separate issue, but running the function that way doesn't seem to find the default Function and the HTTP address/port it provided didn't seem to work.

```log
[11/1/2018 14:59:51] No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).
[11/1/2018 14:59:51] Host initialized (174ms)
[11/1/2018 14:59:51] Host started (192ms)
[11/1/2018 14:59:51] Job host started
Hosting environment: Production
Content root path: C:\dev\ImageDeploy-Backend\PricePredictionFunction
Now listening on: http://0.0.0.0:7071
Application started. Press Ctrl+C to shut down.
Listening on http://0.0.0.0:7071/
Hit CTRL-C to exit...
```

**Comment by veuncent** [comment]
The problem persists for me as well. 
After I ran `dotnet build` manually, I received the following output in my Omnisharp logs:

```
Starting OmniSharp server at 11/2/2018, 9:52:41 AM
    Target: c:\Users\me\Documents\Repositories\azure-function-extract

OmniSharp server started.
    Path: C:\Users\me\.vscode\extensions\ms-vscode.csharp-1.17.0\.omnisharp\1.32.6\OmniSharp.exe
    PID: 17908

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Community 2017 15.8.28010.2046 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin"
            2: StandAlone 15.0 - "C:\Users\me\.vscode\extensions\ms-vscode.csharp-1.17.0\.omnisharp\1.32.6\msbuild\15.0\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Community 2017 15.8.28010.2046 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Users\me\Documents\Repositories\azure-function-extract'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.WorkspaceInitializer
        Project system 'OmniSharp.DotNet.DotNetProjectSystem' is disabled in the configuration.
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'c:\Users\me\Documents\Repositories\azure-function-extract'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\me\Documents\Repositories\azure-function-extract\azure-function-extract.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\me\Documents\Repositories\azure-function-extract'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Users\me\Documents\Repositories\azure-function-extract' on host 12400.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\me\Documents\Repositories\azure-function-extract\azure-function-extract.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\me\Documents\Repositories\azure-function-extract\azure-function-extract.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\me\Documents\Repositories\azure-function-extract\azure-function-extract.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: azure-function-extract
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\me\Documents\Repositories\azure-function-extract\azure-function-extract.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\me\Documents\Repositories\azure-function-extract\azure-function-extract.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\me\Documents\Repositories\azure-function-extract\azure-function-extract.csproj
[warn]: OmniSharp.MSBuild.ProjectLoader
        Could not read state file "obj\Debug\netstandard2.0\azure-function-extract.csprojAssemblyReference.cache". The process cannot access the file 'c:\Users\me\Documents\Repositories\azure-function-extract\obj\Debug\netstandard2.0\azure-function-extract.csprojAssemblyReference.cache' because it is being used by another process.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\me\Documents\Repositories\azure-function-extract\azure-function-extract.csproj'.
c:\Users\me\Documents\Repositories\azure-function-extract\azure-function-extract.csproj
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): Error: Could not read state file "obj\Debug\netstandard2.0\azure-function-extract.csprojAssemblyReference.cache". The process cannot access the file 'c:\Users\me\Documents\Repositories\azure-function-extract\obj\Debug\netstandard2.0\azure-function-extract.csprojAssemblyReference.cache' because it is being used by another process.

[info]: OmniSharp.MSBuild.ProjectManager
        Update project: azure-function-extract
```


Terminal output:
```
PS C:\Users\me\Documents\Repositories\azure-function-extract> dotnet clean
Microsoft (R) Build Engine version 15.8.169+g1ccb72aefa for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 02/11/2018 09:52:50.
     1>Project "C:\Users\me\Documents\Repositories\azure-function-extract\azure-function-extract.csproj" on node 1 (Clean target(s)).
     1>_CleanFunctions:
         Removing directory "C:\Users\me\Documents\Repositories\azure-function-extract\bin\Debug\netstandard2.0\".
     1>Done Building Project "C:\Users\me\Documents\Repositories\azure-function-extract\azure-function-extract.csproj" (Clean target(s)).

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.48
PS C:\Users\me\Documents\Repositories\azure-function-extract> dotnet build
Microsoft (R) Build Engine version 15.8.169+g1ccb72aefa for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restoring packages for C:\Users\me\Documents\Repositories\azure-function-extract\azure-function-extract.csproj...
  Generating MSBuild file C:\Users\me\Documents\Repositories\azure-function-extract\obj\azure-function-extract.csproj.nuget.g.props.
  Restore completed in 1.09 sec for C:\Users\me\Documents\Repositories\azure-function-extract\azure-function-extract.csproj.
  azure-function-extract -> C:\Users\me\Documents\Repositories\azure-function-extract\bin\Debug\netstandard2.0\bin\azure-function-extract.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:05.48
```


And then I ran `func host start` and received similar output to @patridge :
```
PS C:\Users\me\Documents\Repositories\azure-function-extract> func host start

                  %%%%%%
                 %%%%%%
            @   %%%%%%    @
          @@   %%%%%%      @@
       @@@    %%%%%%%%%%%    @@@
     @@      %%%%%%%%%%        @@
       @@         %%%%       @@
         @@      %%%       @@
           @@    %%      @@
                %%
                %

Azure Functions Core Tools (2.1.748 Commit hash: 5db20665cf0c11bedaffc96d81c9baef7456acb3)
Function Runtime Version: 2.0.12134.0
[02/11/2018 08:56:51] Building host: startup suppressed:False, configuration suppressed: False
[02/11/2018 08:56:51] Reading host configuration file 'C:\Users\me\Documents\Repositories\azure-function-extract\host.json'
[02/11/2018 08:56:51] Host configuration file read:
[02/11/2018 08:56:51] {
[02/11/2018 08:56:51]   "version": "2.0",
[02/11/2018 08:56:51]   "functionTimeout": "00:10:00"
[02/11/2018 08:56:51] }
[02/11/2018 08:56:51] Initializing Host.
[02/11/2018 08:56:51] Host initialization: ConsecutiveErrors=0, StartupCount=1
[02/11/2018 08:56:51] Starting JobHost
[02/11/2018 08:56:51] Starting Host (HostId=dell-963890152, InstanceId=0e76551a-c208-4e41-b30f-fac89fd61eb2, Version=2.0.12134.0, ProcessId=18504, AppDomainId=1, Debug=False, FunctionsExtensionVersion=)
[02/11/2018 08:56:51] Loading functions metadata
[02/11/2018 08:56:51] 0 functions loaded
[02/11/2018 08:56:51] Generating 0 job function(s)
[02/11/2018 08:56:51] No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).
[02/11/2018 08:56:51] Host initialized (66ms)
[02/11/2018 08:56:51] Host started (78ms)
[02/11/2018 08:56:51] Job host started
Hosting environment: Production
Content root path: C:\Users\me\Documents\Repositories\azure-function-extract
Now listening on: http://0.0.0.0:7071
Application started. Press Ctrl+C to shut down.
Listening on http://0.0.0.0:7071/
Hit CTRL-C to exit...
[02/11/2018 08:56:58] Host lock lease acquired by instance ID '00000000000000000000000012498461'.
```

[Source code](https://github.com/globaldigitalheritage/azure-function-extract)

**Comment by EricJizbaMSFT** [comment]
@patridge Can you send a screenshot of your folder open in VS Code? Is there a .csproj file at the root of your workspace? If it can't find functions, then you might have the wrong folder open.

@veuncent running `func host start` won't quite work for C#. If you want to run directly from the command line you'd have to do something like this:
```
func host start --script-root bin/debug/netstandard2.0/
```

Your tasks.json should already handle this with the following:
```
"options": {
  "cwd": "${workspaceFolder}/bin/Debug/netstandard2.0"
},
```

**Comment by EricJizbaMSFT** [comment]
I think this boils down to the folder structure of your project. I've opened a separate issue to track work to improve that experience:
https://github.com/Microsoft/vscode-azurefunctions/issues/851
